### ISSUE TITLE
Click feature of Elevation dataset: LiDAR 25m DEM will trigger blank screen

### ISSUE THREAD

**Issue by t83714** [TerriaJS/nationalmap#1205]
### Click feature of Elevation dataset: LiDAR 25m DEM will trigger blank screen

Only happen to Elevation dataset: LiDAR 25m DEM
after the map is loaded, click the feature area (see 2nd screenshot)
If first click doesn’t trigger the blank screen, you might need click multiple times.

With exception:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'PixelValue')
    at y.lookup (3.TerriaMap.js:91:1418)
    at g.escapedValue (3.TerriaMap.js:91:4523)
    at g.renderTokens (3.TerriaMap.js:91:3514)
    at g.render (3.TerriaMap.js:91:3215)
    at e.render (3.TerriaMap.js:91:5027)
    at o.value (3.TerriaMap.js:232:118218)
    at De (3.TerriaMap.js:15:7899)
    at 3.TerriaMap.js:15:121839
    at ye (3.TerriaMap.js:15:5804)
    at e.track (3.TerriaMap.js:15:17464)
```

![image](https://user-images.githubusercontent.com/674387/226528288-b2f605ff-0b74-4c97-a03f-d35dcb7722ca.png)

![image](https://user-images.githubusercontent.com/674387/226528304-9d22fb34-29a7-46d9-be0f-debbfdd1f48b.png)

**Comment by t83714** [comment]
This issue seems also happen to previous version (0.0.20 with terriajs 8.2.22).

**Comment by na9da** [comment]
Fixed in prod - https://nationalmap.gov.au/#share=s-gr3iMI0Fib2WkC7JEZGR2RiDbyQ
